# Site settings
title: My experience in software testing
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.francoislenotre.com" # the base hostname & protocol for your site
contact_title: Contact
email: francois.lenotre@gmail.com
twitter_username: francoislenotre
linkedin_text: LinkedIn 
viadeo_text: Viadeo
# Build settings
markdown: kramdown

#Syntax highlighter
highlighter: rouge

# Setting the encoding to UTF-8 to make sure it will run smoothly under Windows
encoding: utf-8